apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::448049812646:user/wellness-app

      username: wellness-app
      groups:
        - system:masters
