name: Build & Push to ECR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region YOUR-REGION | docker login --username AWS --password-stdin 864899833497.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push image
        run: |
          docker build -t wellness-app .
          docker tag wellness-app:latest 864899833497.dkr.ecr.us-east-1.amazonaws.com/wellness-app:latest
          docker push 864899833497.dkr.ecr.us-east-1.amazonaws.com/wellness-app:latest
